version: "3.9"
services:
  db:
    image: postgres:14
    container_name: circle-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: circle_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: